### PR TITLE
Provide support for a seeds file url

### PR DESCRIPTION
**Pull request by vshlapakov**
One of the requested features is an option to provide a plain text file with a list of seeds instead of passing it one by one, the PR provides exactly this.

Ready for CR, also please let me know if there're any concerns or this behavior is unwelcome for some reason I'm missing, we'll discuss it and find another option. Thanks in advance.

### CODE REVIEW

**Comment by croqaz** [comment]
Hey Viktor, thank you for the PR.

I would suggest maybe to look at the `seeds` and `seed_urls` from the "CrawlerSpider".
And maybe load the items with [util.load_sources](https://github.com/scrapinghub/autoextract-spiders/blob/45d1e49cb6ef84939db8181a7e6ae2bb0e57874e/autoextract_spiders/spiders/util.py#L126) which supports reading from both remote URLs and local seed files.
If there's missing functionality, maybe you can look in there?

The CrawlerSpider already supports loading seeds from remote URLs right now, maybe we can just add the local files like we have in the parent spider here: https://github.com/scrapinghub/autoextract-spiders/blob/7cf5f638d445046f0e4eb3c74fe486c69484f723/autoextract_spiders/spiders/autoextract_spider.py#L140-L147

**Comment by croqaz** [comment]
BTW the util.load_sources file uses requests instead of Scrapy, because long time ago when I was building this spider, I couldn't load seeds from Google Doc shared files with Scrapy, but requests + those headers worked :D 
A lot has changed in the most recend versions of Scrapy, so probably it would work now.

**Comment by vshlapakov** [comment]
Hey Cristi, thanks a ton for the quick response! Using Scrapy to pull the seeds file just looks as a natural way as it's not blocking, so any other seeds/links passed separately might be handled in the background. However if your preference is to use a synchronous blocking approach here, np, I could update the logic like you proposed. I didn't know about `load_sources` helper though, thanks for mentioning it, it doesn't support plain text files (not json/jl) but that's solvable.

UPD Btw another issue with using `requests` instead of Scrapy would be bypassing any Scrapy middlewares and related policies like robots.txt which might be a problem in some specific cases.

**Comment by croqaz** [comment]
Hey Viktor. I don't have any strong preference, feel free to use scrapy, or requests.
About the code:

* can you run the code locally?
* can you write a small update in the readme, how to use the new flag?

**Review by croqaz — APPROVED** [review]
Thank you Viktor! Looks great!

**Comment by kmike** [comment]
Hey! This feature makes sense, and the implementation looks good. A couple of things:

1. Docstring of the CrawlerSpider should be updated as well
2. It seems that because of all the inheritance, CrawlerSpider should already have "articles" and "products" options, which do almost the same thing as seeds-file-url. Not sure what to do about it.

**Comment by vshlapakov** [comment]
Thanks for the CR @kmike!

> Docstring of the CrawlerSpider should be updated as well

Good point, I'll address it in a separate PR :+1: 

> CrawlerSpider should already have "articles" and "products" options

In the current implementation, even if we ignore the explicit types, seed URLs are handled a bit differently than regular item URLs (keeping seeds stats, providing additional meta fields, setting crawlera sessions, maybe smth else I missed). But the idea is kinda similar, I'd agree. 

I would say that despite it seemed like a good idea in the beginning, now the whole inheritance model gets more and more complicated, so I'd suggest to decouple the spiders in the future and use mixins/helpers to share common logic when it's appropriate. Or at least document the current spiders hierarchy with strict definition of what-should-be-done-where.

Also, re "articles" and "products", are we going to maintain the logic? We'll have many other data types coming in the future, I'm afraid we'll need to rework the part as well sooner or later.

**Comment by croqaz** [comment]
I think we can safely delete the "articles" and "products" CLI options, because if we support more verticals in the future, eg: jobs, vehicles, productReviews, etc, this will become more and more complicated.

**Pull request merged**
